### ISSUE TITLE
Sculptor galaxy listed as too small

### ISSUE THREAD

**Issue by djschlegel** [moustakas/LSLGA#27]
Sculptor is in this DES footprint.  It’s radius is listed as muchtoo small, see below, which is probably why those bricks are timing out in DR8.  Even though it has lots of resolved sources, we could probably be treating it just fine like the other LSLGA galaxies with one extended source and whichever point sources are detected within that footprint.

Fornax is the other such Local Group galaxy in our footprint, but it’s listed size is more reasonable.

<img width="833" alt="Screen Shot 2019-06-28 at 8 15 34 PM" src="https://user-images.githubusercontent.com/7918018/60618713-c43f2b80-9d8b-11e9-9b95-b3b5950fa652.png">

**Comment by moustakas** [comment]
Yeah, that's very odd.  In the RC3 the D(25) diameter is ~50 arcmin, which is way more sensible!
http://leda.univ-lyon1.fr/fG.cgi?n=a106&o=ESO351-030

**Comment by moustakas** [comment]
Fixed in the `dr9-fixes` branch.
