### ISSUE TITLE
adjust masks for NGC2366 and NGC0598

### ISSUE THREAD

**Issue by moustakas** [moustakas/LSLGA#29]
NGC2366 is substantially under-masked and NGC0598 less so.

**Comment by deisenstein** [comment]
To be clear, it's possible that you will judge that NGC0598 is masked at a level typical of other LSLGA galaxies and hence should not be adjusted.  It was only a modest signal in the ELGs.

NGC2366 I suspect you will agree is under-masked.

**Comment by moustakas** [comment]
Here's the new, significantly more conservative elliptical mask for NGC2366:
DR8: `D(25)=4.365 arcmin, b/a=0.33, PA=59.5 deg`
DR9: `D(25)=8.8964 arcmin, b/a=0.5263 PA=59.5 deg`

<img width="574" alt="Screen Shot 2019-12-23 at 4 10 14 PM" src="https://user-images.githubusercontent.com/1431820/71380864-ebd6ba00-259e-11ea-8fac-d0aae212aa94.png">

**Comment by moustakas** [comment]
The mask for NGC598 is indeed pretty good/conservative already, I think (see, e.g., https://github.com/moustakas/LSLGA/blob/dr9-fixes/doc/compare-wxsc-largest-galaxies.ipynb) so I'm going to keep it as-is.
