### ISSUE TITLE
ensure MW dwarfs are masked

### ISSUE THREAD

**Issue by moustakas** [moustakas/LSLGA#30]
Draco, Sextans, Leo I, Ursa Minor

**Comment by deisenstein** [comment]
Those are the ones I found in my outlier list, but perhaps others are relevant too.

**Comment by moustakas** [comment]
@deisenstein can you point me to a table of coordinates and radii (and PA and b/a values, if relevant) you would like me to use?

**Comment by moustakas** [comment]
Fornax=ESO356-004 is grossly under-masked in DR8
```
            GALAXY                    RA             DEC        D25       PA       BA
            str29                  float64         float64    float32  float32  float32
----------------------------- ------------------ ----------- --------- ------- ----------
ESO356-004                    39.997150500000004 -34.4491667 12.735031   47.77 0.81096107
```
http://legacysurvey.org/viewer-dev?ra=39.9957&dec=-34.4839&layer=dr8&zoom=9&lslga

**Comment by moustakas** [comment]
The `v5.0` LSLGA catalog contains the following diameter updates/corrections:
* [Fornax=ESO356-004](http://legacysurvey.org/viewer-dev?ra=39.9957&dec=-34.4839&layer=dr8&zoom=9&lslga), new D(25)=70 arcmin via NED (vs 12.7 arcmin previously);
* [Sculptor=ESO351-030](http://legacysurvey.org/viewer-dev?ra=15.0362&dec=-33.7135&layer=dr8&zoom=11&lslga), new D(25)=50.1 arcmin via RC3 (vs 1.14 arcmin previously);
* [Ursa Minor=PGC054074=UGC09749](http://legacysurvey.org/viewer-dev?ra=227.2956&dec=67.2137&layer=dr8&zoom=13&lslga), new D25=30.2 arcmin via NED (vs 0.575 arcmin previously).

I checked [Leo I=PGC2800957](http://legacysurvey.org/viewer-dev?ra=152.1112&dec=12.3065&layer=dr8-model&zoom=11&lslga) and its D25=11.7 arcmin looks OK (but please let me know if you think I should bump this up a bit).

Finally, the following MW dwarfs (are any other ones missing??) were *not* in previous versions of the catalog because they failed my surface brightness cut (which I apply to get rid of mostly junk in the parent Hyperleda catalog), but I've restored them with the following nominal diameters (which looked OK to me):
* [Draco=PGC060095](http://legacysurvey.org/viewer-dev?ra=260.0567&dec=57.9327&layer=dr8-model&zoom=11&lslga), D25=36.8 arcmin;
* [Sextans I=PGC088608](http://legacysurvey.org/viewer-dev?ra=153.2984&dec=-1.6004&layer=dr8&zoom=11&lslga), D25=30 arcmin.

**Comment by moustakas** [comment]
Done in https://github.com/moustakas/LSLGA/commit/2a63333defcc80eaa7a2e201e788fed7bda75281.

**Comment by moustakas** [comment]
According to @arjundey, the following Local Group dwarfs are in the LS/DR9 footprint:
```
             NAME                     RA                 DEC          RADIUS
           bytes29                 float64             float64       float32
----------------------------- ------------------ ------------------- -------
Andromeda VI                  357.94291666666663  24.582499999999996     2.3
Cetus                         6.5458333333333325 -11.044444444444443     3.2
DDO 113                       183.74124999999998  36.218888888888884     0.7
DDO 125                       186.92041666666665   43.49555555555555    1.04
DDO 99                         177.7208333333333   38.88027777777777     0.9
Draco                          260.0516666666666   57.91527777777777    10.0
ESO 294- G 010                 6.639166666666666  -41.85527777777777    0.42
ESO 410- G 005                3.8816666666666664  -32.17999999999999     0.5
Fornax                         39.99708333333333  -34.44916666666666    16.6
GR 8                          194.66833333333332  14.217499999999998    0.32
IC 1613                       16.199166666666663  2.1177777777777775    6.81
IC 5152                       330.67291666666665 -51.296388888888885    0.97
KKH 86                        208.63958333333332   4.243055555555555    0.28
KKR 25                        243.44999999999996  54.371111111111105     0.4
KKR 3                         211.79374999999996   35.06027777777777    0.36
LGS 3 (Local Group Suspect 3) 15.979166666666664  21.884999999999998     2.1
Leo A                         149.86041666666665  30.746388888888884    2.15
Leo I                          152.1170833333333  12.306388888888888     3.4
Leo II                        168.36999999999998  22.151666666666664     2.6
NGC 300                       13.722916666666665  -37.68444444444444     5.0
NGC 4163                      183.03791666666663   36.16916666666666    0.45
NGC 55                        3.7233333333333327  -39.19666666666666    5.16
Phoenix                       27.776249999999997  -44.44472222222222    3.76
Sextans A                      152.7533333333333  -4.692777777777777    2.47
Sextans B                     150.00041666666664   5.332222222222222    1.06
Tucana                        340.45666666666665  -64.41944444444444     1.1
UGC 4879                      139.00916666666666  52.839999999999996    0.41
UGC 8508                      202.68499999999997   54.90999999999999    0.42
UGC 9128                      213.98541666666665  23.055277777777775    0.64
```

Most of these are in the LSLGA, but the following are not:

* Leo II - http://legacysurvey.org/viewer/?ra=168.3638&dec=22.1550&layer=dr8&zoom=12&lslga
* Andromeda VI - http://legacysurvey.org/viewer/?ra=357.9435&dec=24.5798&layer=dr8&zoom=13&lslga
* KKR 25 - http://legacysurvey.org/viewer/?ra=243.4484&dec=54.3704&layer=dr8&zoom=14&lslga

In addition, we probably want the following fixes:
* DDO113 - fix diameter, PA, and axis ratio
* LGS3 - fix diameter
* Phoenix - fix diameter
* Tucana - fix PA

**Comment by moustakas** [comment]
Adding Leo II was not a problem, but KKR25 (http://leda.univ-lyon1.fr/ledacat.cgi?o=kkr25) and Andromeda VI (http://leda.univ-lyon1.fr/ledacat.cgi?o=andromeda%20vi) are not in my parent Hyperleda catalog, so they are going to have to be added using some other mechanism.

**Comment by moustakas** [comment]
Extensive work was done on the MW dwarfs, so the sample is pretty complete now.
